#!/usr/bin/env python

### THIS FILE IS MANAGED BY PUPPET
### <%= file %>

import ConfigParser
import subprocess
import urllib2
import sys
import os
try:
    import json
except ImportError:
    import simplejson as json

def runme(cmd):
    """ run commands in a subprocess and wait for the return code. """
    proc = subprocess.Popen(cmd, \
            shell=True, \
            stdin=subprocess.PIPE, \
            stdout=subprocess.PIPE, \
            stderr=subprocess.PIPE)
    output = proc.communicate()

    return proc.returncode, output

if __name__ == "__main__":
    crons = {}
    users = []
    if os.path.isfile(sys.argv[1]):
        ansible = True
        users.append(file(sys.argv[1]).read())
    else:
        ansible = False
        users.append(sys.argv[1])

    for user in users:
        crons[user] = []
        return_code, output = runme('/usr/bin/crontab -u %s -l' % user)
        if ansible:
            usercrons = output[0].split('\n')
        else:
            usercrons = output[1].split('\n')
        crons[user] = filter(None, usercrons)

    if ansible:
        print json.dumps(crons)
    else:
        print crons
